export const ActionTypes = {
  SET_TRACKS: "SET_TRACKS",
  SELECTED_TRACK: "SELECTED_TRACK",
  REMOVE_TRACK: "REMOVE_TRACK",
  SET_TRACK_TIMES: "SET_TRACK_TIMES",
  SET_SHORTCUT_BREAKDOWN: "SET_SHORTCUT_BREAKDOWN",
  LAP_SHORTCUT_UPDATED: "LAP_SHORTCUT_UPDATED",
};
